# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json

class Component:
    DESCRIPTION = "Add issue label"


class Input:
    LABEL = "label"
    ORGANIZATION = "organization"
    REPOSITORY = "repository"
    ISSUE_NUMBER = "issue_number"
    

class Output:
    URL = "url"
    

class AddIssueLabelInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "label": {
      "type": "string",
      "title": "Label",
      "description": "Label to add",
      "order": 1
    },
    "organization": {
      "type": "string",
      "title": "Organization",
      "description": "Organizational owner of repository",
      "order": 3
    },
    "repository": {
      "type": "string",
      "title": "Repository",
      "description": "Repository to add issue label",
      "order": 2
    },
    "issue_number": {
      "type": "number",
      "title": "ISSUE NUMBER",
      "description": "Issue number",
      "order": 4
    }
  },
  "required": [
    "label",
    "repository",
    "issue_number"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class AddIssueLabelOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "url": {
      "type": "string",
      "title": "URL",
      "description": "URL",
      "order": 1
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
